# Generated by Django 4.2.6 on 2023-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название для меню', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text=('Укажите уникальный идентификатор для меню.', 'Значение этого поля используется для загрузки меню в шаблон.', 'Допустимы латинские буквы, цифры и нижнее подчеркивание(_)'), max_length=256, unique=True, verbose_name='Человекопонятный идентификатор')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
